### PR TITLE
optimise js

### PR DESCRIPTION
**Pull request by BO41**
here are some more cleanups.
I hope I broke nothing and the tests won't fail.

please review :)

### CODE REVIEW

**Comment by tobimensch** [comment]
@BO41 
I glanced over your changes. It seems you traded readability for brevity.

Some of your changes may be good.

@tombh 
This is your decision to make. I won't merge this.

**Comment by BO41** [comment]
@tobimensch do as you like :)
I am just trying to improve the code, but those aren't any game breaking changes anyway and won't make a noticeable difference

**Comment by tombh** [comment]
These mostly seem good. I'm just mostly happy that we're getting PRs, I want to encourage that :)

**Comment by tobimensch** [comment]
@tombh 
That makes me happy as well.

**Pull request merged**
