### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ovidr**
Changed "Why?" to "Why use Browsh?"
Removed avoidable phrases such as "that" and "and uses that"
Divided a run-on sentence by using a period
Switched "Firefox =>57" to "Firefox 57 (or higher)
Shortened the documentation sentence and link

### CODE REVIEW

**Comment by ovidr** [comment]
Hello,
I have made some changes to your README file. The reason is that I am tasked by my professor to help github projects be more easy to read and understand. I have not made any changes to your code.

Thank you for your time.

**Comment by tobimensch** [comment]
I can see why you'd want to remove superfluous words such as somewhat. But I'm not liking all of your changes and one of them looks wrong.

You changed "have feature parity" to "have a feature parity". This doesn't make sense. Either you have reached feature parity or you haven't. You can't have "a feature parity".

**Comment by ovidr** [comment]
Sorry for the mistake. It has been fixed now.
Could you please mention any other changes you do not like?

**Comment by tombh** [comment]
Thanks @ovidr and @tobimensch. The changes look okay now. This text was actually originally written for Texttop, which had a slightly different remit, so I've been thinking about rewriting from scratch at some point. But it's good to have another pair of eyes on the current text, so thanks.

**Pull request merged**
