### PR TITLE
WIP: removing 2 if statements

### PR DESCRIPTION
**Pull request by BO41**
alternatively:
```javascript
    if (!TEST) {
      this._pre_calculated_char = {
        width: 9,
        height: 15
      };
      // TODO: WTF is this magic number? The gap between lines?
      this._char_height_magic_number = 5;
    } else {
      this._pre_calculated_char = {
        width: 1,
        height: 2
      };
      this._char_height_magic_number = 0;
    }
```

### CODE REVIEW

**Comment by BO41** [comment]
if you like such changes, I would have some more :)

why is the test failing?

**Comment by flxwu** [comment]
As far as I can see prettier failed, please lint locally and make sure it passes. (my guess would be that the ternary operator should be broken up in separate lines, but please check it yourself 🙂 )

**Comment by tombh** [comment]
Yeah, agreed thanks for the PR! And would def like to see more PRs like this :)

If you've installed all the deps you can easily fix linting errors with:
`gofmt -s -w interfacer/`
`cd webext && ./node_modules/.bin/prettier --write "{src,test}/**/*.js"`

**Comment by tombh** [comment]
Did you run `./node_modules/.bin/prettier --write "{src,test}/**/*.js"`?

**Comment by BO41** [comment]
@tombh I did now. But it did change some other files as well. I am not sure if this is okay

**Comment by tombh** [comment]
Tests pass, it's merged! Thank you :)

**Comment by BO41** [comment]
@tombh I set the name to "WIP: " because I have some other changes I like to propose and don't want to open many PR's, but never mind. I will just open a new PR as soon as I am done :)

**Comment by tombh** [comment]
Oh I see, that was a good idea. Never mind. I'll remember that for next time :)

**Pull request merged**
