### PR TITLE
Change font family, fix invalid CSS (fixes #70)

### LINKED ISSUE #70: Wrong font-size on Wikipedia articles
When browsing [Wikipedia](https://html.brow.sh/https://en.wikipedia.org/wiki/Internet) using Chrome/Firefox on Windows 10 with `devicePixelRatio=1.25`, the article text has too small left padding (see screenshot below). Setting the `font-size: 16.5px;` on `body` fixes this problem.

screenshot

### PR DESCRIPTION
**Pull request by niutech**
CSS values `image-rendering: optimizeSpeed` and `optimize-contrast` are invalid, as are `// single-line comments`.
Now with `font-family: 'Courier New', monospace` a web page text fits its background image (issue #70).

### CODE REVIEW

**Comment by tobimensch** [comment]
@niutech 
Thanks for your pull request.

Through the linked issue it appears you're using "Windows 10 with devicePixelRatio=1.25".

Did you test your patch with any other system, i.e. Linux?

**Comment by niutech** [comment]
No, right now I have only Windows 10 machine, I will test it as soon as I get to the Linux computer.
Meanwhile I have changed the PR not to change the font-size, but to use Courier New font if available, because it fixes the issue with font width (default monospace on Windows 10 is Consolas, which is narrower).

**Comment by tobimensch** [comment]
@niutech 
You probably know this, however I just wanted to mention that you could also test this in a Linux virtual machine on Windows.

**Comment by niutech** [comment]
Yes, I'll post some screenshots when I test it in Linux.

**Comment by niutech** [comment]
OK, I have tested the changes under Lubuntu Linux. Here is Chromium with default monospace font:
chromium-monospace

Here is Chromium with 'Courier New' font:
chromium-courier-new

And here is Firefox with the new font:
firefox-courier-new

The new font does not break page layout nor change font size on Linux, but it fixes the layout on Windows 10, so I propose to merge this fix.

As a side note, I think the default width (number of columns) on html.brow.sh is too narrow for today's screen sizes. I would increase it to at least 120.

Thanks!

**Comment by tombh** [comment]
Thanks so much for this, for doing the research, finding a fix and submitting the screenshots. I'm happy to merge this. Just one thing, but don't worry if you don't get round to it, could you squash these 2 commits and just create a little commit message giving the context to these changes.

**Comment by niutech** [comment]
You can easily squash commits by yourself while merging: https://github.blog/2016-04-01-squash-your-commits/

**Comment by niutech** [comment]
@tombh Will you merge this PR?

**Comment by tombh** [comment]
Sorry for the delay. By asking you to rebase I was hoping you'd be able to better name and describe the commit. Then I just forgot about it.

**Pull request merged**
